[project]
name = "knowledge-building"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "islp>=0.4.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
